### ISSUE TITLE
Template feedback

### ISSUE THREAD

**Issue by familyfriendlymikey** [imba/imba-vite-template#14]
Finally had a chance to use this template and it works super well, thank you guys for your work on it.

I think this template is good as a slightly larger example, but my thinking is that when beginners download a template and there are so many different files, it can be a little overwhelming.

Both beginners and experienced people alike may not notice that you don't actually *need* any of it. I really think one of the strong selling points of Imba is that you can literally make one file like this
```
imba.mount <div> "hello world"
```
And that's *all* you need.

I understand we're juggling concerns here, as in we want to show what the possibilities are (testing, css and component imports, etc.) With that in mind I have a few suggestions that I'm willing to work on if you guys agree:
- Currently `imba create` only has two templates, and then it prompts you for like 4 more things which is annoying. `imba create` should prompt for one thing only, a choice of template (and it should also provide a flag for choosing template as well).
- In that list of templates, we could have:
	- `default (vite)`: A stripped down version of the current `imba-vite-template`, described in next bullet point.
	- `holistic (vite)`: The current `imba-vite-template`, maybe there's a better name.
	- `static (vite)`
	- `web (esbuild)`
	- `electron (esbuild)`
- In the default vite template, the app will look exactly the same as it is now, except we:
	- Remove all tests.
	- Remove all imports.
	- Use only imba css.
	- Put some inline comments to explain each part.
	- Move `public/vite.svg` to the same place as the imba svg.
	- Remove index.html and main.js.
	- I'd like to remove some of the config files, or if possible move them to a `.config` folder or something, but I'm probably in the minority one on this one :P

- Regarding `imba create`, this is what it currently prompts and what I think we should do instead:
	- Template: we should keep this option.
	- Project name: remove this option.
		- If no project name is provided, `imba create` should print "Must provide project name or `.` for current folder" and exit.
		- If the project folder (other than `.`) already exists, print "Folder `<name>` already exists, you can choose a different name or use `imba create .` to create in an existing folder" and exit.
	- Configure package.json: remove this option.
		- I don't think I've ever done this in my life. Okay, I've done it a few times. But still, this can just be a flag `--configure` or something.
	- Confirm project creation in directory: modify this option.
		- If a user chose `.` as the project, prompt for confirmation. Otherwise, we don't need to because the project folder doesn't exist so even if it's a mistake there's no harm to their system.

**Comment by familyfriendlymikey** [comment]
Example of stripped down template on [my fork](https://github.com/familyfriendlymikey/imba-vite-template).

I also made some CSS additions and changed the text a bit. Not final but let me know what you think!

**Comment by MystPi** [comment]
Nice; a stripped-down version of the template is just what I needed! I have one minor "issue": instead of `index.html` importing `src/index.js`, which imports `src/main.imba`, wouldn't it be possible to simply have `index.html` import `src/main.imba`? I'm pretty sure Vite allows you to do that.

**Comment by familyfriendlymikey** [comment]
@MystPi Btw, a variation of the stripped down template is now the default Vite template (`imba create -t vite`) 🙂
