### ISSUE TITLE
Explain `imba.mount` with and without targeting an element by ID

### ISSUE THREAD

**Issue by codeluggage** [imba/imba-vite-template#4]
> Looks good :) One minor nitpick about the template itself. I would usually not include the `<div id='app'>` in the html, and then instead do `imba.mount <app>` without the `document.getElementById` in main.imba. But I know most of the frameworks follow the other convention, so it might be best to stick with it?

That was my exact thought as well @somebee - I actually changed it back and forth for https://github.com/imba/imba-base-template and had a commented out version with some tutorial explanation saying you could chose which way to do it. 

Another strong argument in favor of targeting the element ID directly is that it would be easier to incrementally adopt Imba, instead of thinking you have to change the entire project to have the root of the project based on Imba. 

Perhaps the best next step here is to add a comment in the code explaining both approaches?

_Originally posted by @codeluggage in https://github.com/imba/imba-vite-template/issues/3#issuecomment-1243318156_

**Comment by haikyuu** [comment]
> Another strong argument in favor of targeting the element ID directly is that it would be easier to incrementally adopt Imba, instead of thinking you have to change the entire project to have the root of the project based on Imba.

Totally agree, Incremental adoption is very important. Let's keep it as is.

More experienced developers will remove it if they want to. This is more targetted towards newcomers :)
